version: 2.1
orbs:
  nais: 'navikt/nais-deployment@3.2.0'

jobs:
  build:
    working_directory: ~/k9-selvbetjening-oppslag
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew check shadowJar
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - nais/docker:
          registry: docker.pkg.github.com
          image: navikt/k9-selvbetjening-oppslag/k9-selvbetjening-oppslag
          tag: $(git rev-parse --short HEAD)

workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - build:
          context: Düsseldorf
          filters:
            branches:
              only:
                - master
      - nais/deploy-gh-app:
          name: dev-deploy
          build-and-push-docker-image: false
          repo: navikt/k9-selvbetjening-oppslag
          image: docker.pkg.github.com/navikt/k9-selvbetjening-oppslag/k9-selvbetjening-oppslag
          tag: $(git rev-parse --short HEAD)
          github-app-id: 35124
          nais-template: nais/dev-fss.yml
          environment: dev-fss
          team: dusseldorf
          filters:
            branches:
              only:
                - master
          requires:
            - build