apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-selvbetjening-oppslag
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://k9-selvbetjening-oppslag.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  webproxy: true
  env:
    - name: LOGIN_SERVICE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    - name: PERSON_V3_URL
      value: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
    - name: ARBEIDSGIVER_OG_ARBEIDSTAKER_V1_URL
      value: https://modapp-q1.adeo.no/aareg-core/api
    - name: AKTOER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: ENHET_V1_URL
      value: https://modapp-q1.adeo.no/ereg/api/v1/
    - name: WS_STS_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: REST_TOKEN_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
