apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  accessPolicy:
    inbound:
      rules:
        - application: k9-ettersending-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: omsorgspengerutbetaling-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: omsorgspengerutbetalingsoknad-arbeidstaker-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: pleiepengesoknad-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: pleiepenger-livets-sluttfase-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: omsorgsdager-melding-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: omsorgsdager-aleneomsorg-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: k9-brukerdialog-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
        - application: k9-sak-innsyn-api
          cluster: {{environment}}-gcp
          namespace: {{namespace}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: {{app}}
