apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-selvbetjening-oppslag
  namespace: default
  labels:
    team: dusseldorf
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://k9-selvbetjening-oppslag.nais.adeo.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  webproxy: true
  env:
    - name: LOGIN_SERVICE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    - name: ARBEIDSGIVER_OG_ARBEIDSTAKER_V1_URL
      value: https://modapp.adeo.no/aareg-services/api/v1
    - name: AKTOER_V1_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: ENHET_V1_URL
      value: https://modapp.adeo.no/ereg/api/v1/
    - name: REST_TOKEN_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: TPS_PROXY_V1_URL
      value: https://tps-proxy.nais.adeo.no/api/v1
